#!/bin/bash
set -e

# ── Defaults ────────────────────────────────────────────────────────────────
VARIANT="${VARIANT:-durable-state}"          # massive | context-aware | durable-state
PROJECT_DIR="${PROJECT_DIR:-$HOME/Research/autonomous-project}"
PROJECT_NAME="${PROJECT_NAME:-autonomous-project}"
GOAL="${GOAL:-}"
PR_EVERY="${PR_EVERY:-0}"                   # 0 = no PR gating; N = create PR every N commits

# ── Usage ───────────────────────────────────────────────────────────────────
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --goal GOAL          Project description (required, or set GOAL env var)"
    echo "  --variant VARIANT    'massive' (single), 'context-aware' (two-model), 'durable-state' (evidence-based, default)"
    echo "  --project-dir DIR    Working directory (default: ~/Research/autonomous-project)"
    echo "  --project-name NAME  GitHub repo name (default: autonomous-project)"
    echo "  --pr-every N         Create a PR every N commits (0 = disabled, gates context size)"
    echo "  --help               Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --goal 'Build a CLI tool called foo with bar and baz features'"
    echo "  $0 --goal 'Build something' --variant durable-state --pr-every 10"
    echo "  VARIANT=durable-state PR_EVERY=10 $0 --goal 'Build something'"
    exit 0
}

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --goal) GOAL="$2"; shift 2 ;;
        --variant) VARIANT="$2"; shift 2 ;;
        --project-dir) PROJECT_DIR="$2"; shift 2 ;;
        --project-name) PROJECT_NAME="$2"; shift 2 ;;
        --pr-every) PR_EVERY="$2"; shift 2 ;;
        --help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

if [ -z "$GOAL" ]; then
    echo "Error: --goal is required (or set GOAL env var)"
    usage
fi

# ── Select spoke ────────────────────────────────────────────────────────────
SPOKE_DIR="$HOME/Research/four/examples/spokes"
case "$VARIANT" in
    massive)
        SPOKE="$SPOKE_DIR/massive-feature-implementation.py"
        ;;
    context-aware)
        SPOKE="$SPOKE_DIR/context-aware-implementation.py"
        ;;
    durable-state)
        SPOKE="$SPOKE_DIR/durable-state-implementation.py"
        ;;
    long-running)
        SPOKE="$SPOKE_DIR/long-running-implementation.py"
        ;;
    *)
        echo "Error: unknown variant '$VARIANT' (use 'massive', 'context-aware', 'durable-state', or 'long-running')"
        exit 1
        ;;
esac

if [ ! -f "$SPOKE" ]; then
    echo "Error: spoke not found: $SPOKE"
    exit 1
fi

# ── Setup project dir ───────────────────────────────────────────────────────
echo "Setting up project at $PROJECT_DIR"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

if [ ! -d ".git" ]; then
    git init
    git commit --allow-empty -m "initial"
fi

# ── PR gating via git post-commit hook ──────────────────────────────────────
# Physical compaction: every N commits, create a PR branch and push it.
# The PR is the gate — the durable record of a batch of work.
setup_pr_gate() {
    local gate_file="$PROJECT_DIR/.pr_gate_state"
    echo "$(git rev-parse HEAD)" > "$gate_file"
    echo "0" >> "$gate_file"

    cat > "$PROJECT_DIR/.git/hooks/post-commit" << 'HOOKEOF'
#!/bin/bash
GATE_FILE="$(git rev-parse --show-toplevel)/.pr_gate_state"
PR_EVERY="${PR_EVERY:-0}"
[ "$PR_EVERY" -le 0 ] && exit 0

OLD_HASH=$(sed -n '1p' "$GATE_FILE")
PR_NUM=$(sed -n '2p' "$GATE_FILE")
COMMITS=$(git rev-list --count "$OLD_HASH"..HEAD 2>/dev/null || echo 0)

if [ "$COMMITS" -ge "$PR_EVERY" ]; then
    PR_NUM=$((PR_NUM + 1))
    BRANCH="autonomous/pr-${PR_NUM}"
    echo "=== PR GATE: ${COMMITS} commits, creating $BRANCH ==="
    git checkout -b "$BRANCH" 2>/dev/null
    git push origin "$BRANCH"
    LOGS=$(git log --oneline "$OLD_HASH"..HEAD)
    gh pr create \
        --base main \
        --head "$BRANCH" \
        --title "Autonomous batch ${PR_NUM}: ${COMMITS} commits" \
        --body "Generated by four autonomous pipeline.\n\n\`\`\`\n${LOGS}\n\`\`\`" \
        2>&1 || echo "PR create failed"
    git checkout main 2>/dev/null
    echo "$(git rev-parse HEAD)" > "$GATE_FILE"
    echo "$PR_NUM" >> "$GATE_FILE"
    echo "=== PR GATE: done (PR #$PR_NUM) ==="
fi
HOOKEOF
    chmod +x "$PROJECT_DIR/.git/hooks/post-commit"
}

# ── Push to remote on exit ──────────────────────────────────────────────────
cleanup() {
    echo "Pushing to remote..."
    git add -A 2>/dev/null || true
    git commit -m "autonomous: save progress" 2>/dev/null || true
    if ! git remote -v | grep -q "origin"; then
        REMOTE_URL="https://github.com/belarusian/${PROJECT_NAME}.git"
        echo "Creating GitHub repo: $PROJECT_NAME"
        gh repo create "belarusian/$PROJECT_NAME" --public --source=. --remote=origin --push 2>/dev/null || \
        (git remote add origin "$REMOTE_URL" 2>/dev/null; git push -u origin main 2>/dev/null) || true
    else
        git push 2>/dev/null || true
    fi
}
trap cleanup EXIT

# ── Initialize gate state ───────────────────────────────────────────────────
if [ "$PR_EVERY" -gt 0 ]; then
    setup_pr_gate
    echo "PR gating enabled: will create PR every $PR_EVERY commits (via post-commit hook)"
fi

# ── Run ─────────────────────────────────────────────────────────────────────
echo "Variant:   $VARIANT"
echo "Spoke:     $SPOKE"
echo "PR gating: every $PR_EVERY commits"
echo "Goal:      $GOAL"
echo "---"

FIVE_BASE_URL=http://192.168.1.157:8080/v1 \
FIVE_MODEL=fast-qwen \
FIVE_LARGE_URL=http://192.168.1.161:8081/v1 \
FIVE_LARGE_MODEL=qwen \
FIVE_MAX_TOKENS=65536 \
PR_EVERY="$PR_EVERY" \
python "$SPOKE" --goal "$GOAL"
