#!/bin/bash
set -e

# ── Defaults ────────────────────────────────────────────────────────────────
VARIANT="${VARIANT:-durable-state}"          # massive | context-aware | durable-state
PROJECT_DIR="${PROJECT_DIR:-$HOME/Research/autonomous-project}"
PROJECT_NAME="${PROJECT_NAME:-autonomous-project}"
GOAL="${GOAL:-}"
PR_EVERY="${PR_EVERY:-0}"                   # 0 = no PR gating; N = create PR every N commits

# ── Usage ───────────────────────────────────────────────────────────────────
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --goal GOAL          Project description (required, or set GOAL env var)"
    echo "  --variant VARIANT    'massive' (single), 'context-aware' (two-model), 'durable-state' (evidence-based, default)"
    echo "  --project-dir DIR    Working directory (default: ~/Research/autonomous-project)"
    echo "  --project-name NAME  GitHub repo name (default: autonomous-project)"
    echo "  --pr-every N         Create a PR every N commits (0 = disabled, gates context size)"
    echo "  --help               Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --goal 'Build a CLI tool called foo with bar and baz features'"
    echo "  $0 --goal 'Build something' --variant durable-state --pr-every 10"
    echo "  VARIANT=durable-state PR_EVERY=10 $0 --goal 'Build something'"
    exit 0
}

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --goal) GOAL="$2"; shift 2 ;;
        --variant) VARIANT="$2"; shift 2 ;;
        --project-dir) PROJECT_DIR="$2"; shift 2 ;;
        --project-name) PROJECT_NAME="$2"; shift 2 ;;
        --pr-every) PR_EVERY="$2"; shift 2 ;;
        --help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

if [ -z "$GOAL" ]; then
    echo "Error: --goal is required (or set GOAL env var)"
    usage
fi

# ── Select spoke ────────────────────────────────────────────────────────────
SPOKE_DIR="$HOME/Research/four/examples/spokes"
case "$VARIANT" in
    massive)
        SPOKE="$SPOKE_DIR/massive-feature-implementation.py"
        ;;
    context-aware)
        SPOKE="$SPOKE_DIR/context-aware-implementation.py"
        ;;
    durable-state)
        SPOKE="$SPOKE_DIR/durable-state-implementation.py"
        ;;
    long-running)
        SPOKE="$SPOKE_DIR/long-running-implementation.py"
        ;;
    *)
        echo "Error: unknown variant '$VARIANT' (use 'massive', 'context-aware', 'durable-state', or 'long-running')"
        exit 1
        ;;
esac

if [ ! -f "$SPOKE" ]; then
    echo "Error: spoke not found: $SPOKE"
    exit 1
fi

# ── Setup project dir ───────────────────────────────────────────────────────
echo "Setting up project at $PROJECT_DIR"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

if [ ! -d ".git" ]; then
    git init
    git commit --allow-empty -m "initial"
fi

# ── PR gating helper ────────────────────────────────────────────────────────
# Physical compaction: every N commits, create a PR branch and push it.
# The PR is the gate — the durable record of a batch of work.
PR_COUNTER=0
BASE_COMMIT=""

gate_pr() {
    local commits_since_gate=$(git rev-list --count "$BASE_COMMIT"..HEAD 2>/dev/null || echo 0)
    if [ "$commits_since_gate" -ge "$PR_EVERY" ]; then
        local pr_num=$((PR_COUNTER + 1))
        local pr_branch="autonomous/pr-${pr_num}"
        echo ""
        echo "=== PR GATE: creating $pr_branch ($commits_since_gate commits since last gate) ==="
        git checkout -b "$pr_branch" 2>/dev/null || git checkout "$pr_branch" 2>/dev/null
        git push origin "$pr_branch" 2>/dev/null || true
        # Create PR via gh if available
        local pr_title="Autonomous batch ${pr_num}: $commits_since_gate commits"
        local pr_body="Generated by four autonomous pipeline (variant: $VARIANT).\n\nCommits in this batch:\n\`\`\`\n$(git log --oneline "$BASE_COMMIT"..HEAD)\n\`\`\`"
        if command -v gh &>/dev/null; then
            gh pr create \
                --base main \
                --head "$pr_branch" \
                --title "$pr_title" \
                --body "$pr_body" \
                2>/dev/null || true
        fi
        git checkout main 2>/dev/null || true
        BASE_COMMIT=$(git rev-parse HEAD)
        PR_COUNTER=$pr_num
        echo "=== PR GATE: done (PR #$pr_num) ==="
        echo ""
    fi
}

# ── Push to remote on exit ──────────────────────────────────────────────────
cleanup() {
    echo "Pushing to remote..."
    git add -A 2>/dev/null || true
    git commit -m "autonomous: save progress" 2>/dev/null || true
    if [ "$PR_EVERY" -gt 0 ]; then
        gate_pr
    fi
    if ! git remote -v | grep -q "origin"; then
        REMOTE_URL="https://github.com/belarusian/${PROJECT_NAME}.git"
        echo "Creating GitHub repo: $PROJECT_NAME"
        gh repo create "belarusian/$PROJECT_NAME" --public --source=. --remote=origin --push 2>/dev/null || \
        (git remote add origin "$REMOTE_URL" 2>/dev/null; git push -u origin main 2>/dev/null) || true
    else
        git push 2>/dev/null || true
    fi
}
trap cleanup EXIT

# ── Initialize gate state ───────────────────────────────────────────────────
if [ "$PR_EVERY" -gt 0 ]; then
    BASE_COMMIT=$(git rev-parse HEAD)
    echo "PR gating enabled: will create PR every $PR_EVERY commits"
fi

# ── Run ─────────────────────────────────────────────────────────────────────
echo "Variant:   $VARIANT"
echo "Spoke:     $SPOKE"
echo "PR gating: every $PR_EVERY commits"
echo "Goal:      $GOAL"
echo "---"

FIVE_BASE_URL=http://192.168.1.157:8080/v1 \
FIVE_MODEL=fast-qwen \
FIVE_LARGE_URL=http://192.168.1.161:8081/v1 \
FIVE_LARGE_MODEL=qwen \
FIVE_MAX_TOKENS=65536 \
PR_EVERY="$PR_EVERY" \
BASE_COMMIT="$BASE_COMMIT" \
python "$SPOKE" --goal "$GOAL"

# Final gate check after run completes
if [ "$PR_EVERY" -gt 0 ]; then
    gate_pr
fi
