#!/bin/bash
set -e

# ── Defaults ────────────────────────────────────────────────────────────────
VARIANT="${VARIANT:-stream}"                 # stream | documentation | pr-consolidation
PROJECT_DIR="${PROJECT_DIR:-$HOME/Research/autonomous-project}"
PROJECT_NAME="${PROJECT_NAME:-autonomous-project}"
GOAL="${GOAL:-}"

# ── Usage ───────────────────────────────────────────────────────────────────
usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --goal GOAL          Project description (required, or set GOAL env var)"
    echo "  --variant VARIANT    'stream' (unimpeded code flow, default), 'documentation' (post-hoc docs), 'pr-consolidation' (post-hoc PRs)"
    echo "  --project-dir DIR    Working directory (default: ~/Research/autonomous-project)"
    echo "  --project-name NAME  GitHub repo name (default: autonomous-project)"
    echo "  --help               Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 --goal 'Build a CLI tool called foo with bar and baz features'"
    echo "  VARIANT=documentation $0 --goal 'Document the existing codebase'"
    echo "  VARIANT=pr-consolidation $0 --goal 'Consolidate commits into semantic PRs'"
    exit 0
}

# ── Parse args ──────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --goal) GOAL="$2"; shift 2 ;;
        --variant) VARIANT="$2"; shift 2 ;;
        --project-dir) PROJECT_DIR="$2"; shift 2 ;;
        --project-name) PROJECT_NAME="$2"; shift 2 ;;
        --help) usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

if [ -z "$GOAL" ]; then
    echo "Error: --goal is required (or set GOAL env var)"
    usage
fi

# ── Select spoke ────────────────────────────────────────────────────────────
SPOKE_DIR="$HOME/Research/four/examples/spokes"
case "$VARIANT" in
    stream)
        SPOKE="$SPOKE_DIR/stream-implementation.py"
        ;;
    documentation)
        SPOKE="$SPOKE_DIR/documentation-implementation.py"
        ;;
    pr-consolidation)
        SPOKE="$SPOKE_DIR/pr-consolidation-implementation.py"
        ;;
    context-aware)
        SPOKE="$SPOKE_DIR/context-aware-implementation.py"
        ;;
    durable-state)
        SPOKE="$SPOKE_DIR/durable-state-implementation.py"
        ;;
    long-running)
        SPOKE="$SPOKE_DIR/long-running-implementation.py"
        ;;
    massive)
        SPOKE="$SPOKE_DIR/massive-feature-implementation.py"
        ;;
    *)
        echo "Error: unknown variant '$VARIANT' (use 'stream', 'documentation', 'pr-consolidation', 'context-aware', 'durable-state', 'long-running', or 'massive')"
        exit 1
        ;;
esac

if [ ! -f "$SPOKE" ]; then
    echo "Error: spoke not found: $SPOKE"
    exit 1
fi

# ── Setup project dir ───────────────────────────────────────────────────────
echo "Setting up project at $PROJECT_DIR"
mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"

if [ ! -d ".git" ]; then
    git init
    git commit --allow-empty -m "initial"
fi

# ── PR creation on exit (replaces noisy "save progress" commits) ────────────
cleanup() {
    # Check if there are actual changes (not just trajectories)
    git add -A 2>/dev/null || true
    CHANGED_FILES=$(git diff --cached --name-only | grep -v "trajectories/" | wc -l)

    if [ "$CHANGED_FILES" -gt 0 ]; then
        # Create a PR branch with the changes
        PR_BRANCH="autonomous/$(date +%Y%m%d%H%M%S)"
        git checkout -b "$PR_BRANCH" 2>/dev/null
        git commit -m "autonomous: batch complete" 2>/dev/null || true
        git push origin "$PR_BRANCH" 2>/dev/null || true

        # Create PR
        COMMITS=$(git log --oneline HEAD..origin/main 2>/dev/null | wc -l)
        gh pr create \
            --base main \
            --head "$PR_BRANCH" \
            --title "Autonomous batch: $VARIANT pipeline" \
            --body "Generated by four autonomous pipeline (variant: $VARIANT).\n\nChanges: ${CHANGED_FILES} files.\n\nRun \`bash run-massive-implementation.sh --variant pr-review --pr <PR_NUM>\` to review." \
            2>/dev/null || true

        # Return to main
        git checkout main 2>/dev/null || true
    else
        # No real changes, just push trajectories
        git push origin main 2>/dev/null || true
    fi
}
trap cleanup EXIT

# ── Run ─────────────────────────────────────────────────────────────────────
echo "Variant:   $VARIANT"
echo "Spoke:     $SPOKE"
echo "Goal:      $GOAL"
echo "---"

FIVE_BASE_URL=http://192.168.1.157:8080/v1 \
FIVE_MODEL=fast-qwen \
FIVE_LARGE_URL=http://192.168.1.161:8081/v1 \
FIVE_LARGE_MODEL=qwen \
FIVE_MAX_TOKENS=65536 \
python "$SPOKE" --goal "$GOAL"
